spring:
  datasource:
    # Thêm tham số connectTimeout và socketTimeout để App kiên nhẫn hơn
    url: jdbc:postgresql://localhost:5433/bakery_db?connectTimeout=30&socketTimeout=30
    username: postgres
    password: postgres
  jpa:
    # Ép kiểu Dialect để không cần Hibernate đi dò tìm nữa (Fix lỗi Dialect)
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080